export const countries = [
  {
    letter: 'A',
    countries: [
      { code: 'AF', name: '阿富汗' },
      { code: 'AL', name: '阿尔巴尼亚' },
      { code: 'DZ', name: '阿尔及利亚' },
      { code: 'AD', name: '安道尔' },
      { code: 'AO', name: '安哥拉' },
      { code: 'AR', name: '阿根廷' },
      { code: 'AM', name: '亚美尼亚' },
      { code: 'AU', name: '澳大利亚' },
      { code: 'AT', name: '奥地利' },
      { code: 'AZ', name: '阿塞拜疆' },
    ],
  },
  {
    letter: 'B',
    countries: [
      { code: 'BS', name: '巴哈马' },
      { code: 'BH', name: '巴林' },
      { code: 'BD', name: '孟加拉国' },
      { code: 'BY', name: '白俄罗斯' },
      { code: 'BE', name: '比利时' },
      { code: 'BZ', name: '伯利兹' },
      { code: 'BJ', name: '贝宁' },
      { code: 'BT', name: '不丹' },
      { code: 'BO', name: '玻利维亚' },
      { code: 'BR', name: '巴西' },
    ],
  },
  {
    letter: 'C',
    countries: [
      { code: 'KH', name: '柬埔寨' },
      { code: 'CM', name: '喀麦隆' },
      { code: 'CA', name: '加拿大' },
      { code: 'CF', name: '中非共和国' },
      { code: 'TD', name: '乍得' },
      { code: 'CL', name: '智利' },
      { code: 'CN', name: '中国' },
      { code: 'CO', name: '哥伦比亚' },
      { code: 'CG', name: '刚果' },
      { code: 'CR', name: '哥斯达黎加' },
      { code: 'HR', name: '克罗地亚' },
      { code: 'CU', name: '古巴' },
      { code: 'CY', name: '塞浦路斯' },
      { code: 'CZ', name: '捷克共和国' },
    ],
  },
  {
    letter: 'D',
    countries: [
      { code: 'DK', name: '丹麦' },
      { code: 'DJ', name: '吉布提' },
      { code: 'DO', name: '多米尼加共和国' },
    ],
  },
  {
    letter: 'E',
    countries: [
      { code: 'EC', name: '厄瓜多尔' },
      { code: 'EG', name: '埃及' },
      { code: 'SV', name: '萨尔瓦多' },
      { code: 'GQ', name: '赤道几内亚' },
      { code: 'ER', name: '厄立特里亚' },
      { code: 'EE', name: '爱沙尼亚' },
      { code: 'ET', name: '埃塞俄比亚' },
    ],
  },
  {
    letter: 'F',
    countries: [
      { code: 'FJ', name: '斐济' },
      { code: 'FI', name: '芬兰' },
      { code: 'FR', name: '法国' },
    ],
  },
  {
    letter: 'G',
    countries: [
      { code: 'GA', name: '加蓬' },
      { code: 'GM', name: '冈比亚' },
      { code: 'GE', name: '格鲁吉亚' },
      { code: 'DE', name: '德国' },
      { code: 'GH', name: '加纳' },
      { code: 'GR', name: '希腊' },
      { code: 'GL', name: '格陵兰' },
      { code: 'GT', name: '危地马拉' },
      { code: 'GN', name: '几内亚' },
    ],
  },
  {
    letter: 'H',
    countries: [
      { code: 'HT', name: '海地' },
      { code: 'HN', name: '洪都拉斯' },
      { code: 'HK', name: '中国香港' },
      { code: 'HU', name: '匈牙利' },
    ],
  },
  {
    letter: 'I',
    countries: [
      { code: 'IS', name: '冰岛' },
      { code: 'IN', name: '印度' },
      { code: 'ID', name: '印度尼西亚' },
      { code: 'IR', name: '伊朗' },
      { code: 'IQ', name: '伊拉克' },
      { code: 'IE', name: '爱尔兰' },
      { code: 'IL', name: '以色列' },
      { code: 'IT', name: '意大利' },
    ],
  },
  {
    letter: 'J',
    countries: [
      { code: 'JM', name: '牙买加' },
      { code: 'JP', name: '日本' },
      { code: 'JO', name: '约旦' },
    ],
  },
  {
    letter: 'K',
    countries: [
      { code: 'KZ', name: '哈萨克斯坦' },
      { code: 'KE', name: '肯尼亚' },
      { code: 'KP', name: '朝鲜' },
      { code: 'KR', name: '韩国' },
      { code: 'KW', name: '科威特' },
      { code: 'KG', name: '吉尔吉斯斯坦' },
    ],
  },
  {
    letter: 'L',
    countries: [
      { code: 'LA', name: '老挝' },
      { code: 'LV', name: '拉脱维亚' },
      { code: 'LB', name: '黎巴嫩' },
      { code: 'LS', name: '莱索托' },
      { code: 'LR', name: '利比里亚' },
      { code: 'LY', name: '利比亚' },
      { code: 'LI', name: '列支敦士登' },
      { code: 'LT', name: '立陶宛' },
      { code: 'LU', name: '卢森堡' },
    ],
  },
  {
    letter: 'M',
    countries: [
      { code: 'MO', name: '中国澳门' },
      { code: 'MG', name: '马达加斯加' },
      { code: 'MW', name: '马拉维' },
      { code: 'MY', name: '马来西亚' },
      { code: 'MV', name: '马尔代夫' },
      { code: 'ML', name: '马里' },
      { code: 'MT', name: '马耳他' },
      { code: 'MX', name: '墨西哥' },
      { code: 'MD', name: '摩尔多瓦' },
      { code: 'MC', name: '摩纳哥' },
      { code: 'MN', name: '蒙古' },
      { code: 'ME', name: '黑山' },
      { code: 'MA', name: '摩洛哥' },
      { code: 'MZ', name: '莫桑比克' },
      { code: 'MM', name: '缅甸' },
    ],
  },
  {
    letter: 'N',
    countries: [
      { code: 'NA', name: '纳米比亚' },
      { code: 'NP', name: '尼泊尔' },
      { code: 'NL', name: '荷兰' },
      { code: 'NZ', name: '新西兰' },
      { code: 'NI', name: '尼加拉瓜' },
      { code: 'NE', name: '���日尔' },
      { code: 'NG', name: '尼日利亚' },
      { code: 'NO', name: '挪威' },
    ],
  },
  {
    letter: 'O',
    countries: [{ code: 'OM', name: '阿曼' }],
  },
  {
    letter: 'P',
    countries: [
      { code: 'PK', name: '巴基斯坦' },
      { code: 'PS', name: '巴勒斯坦' },
      { code: 'PA', name: '巴拿马' },
      { code: 'PY', name: '巴拉圭' },
      { code: 'PE', name: '秘鲁' },
      { code: 'PH', name: '菲律宾' },
      { code: 'PL', name: '波兰' },
      { code: 'PT', name: '葡萄牙' },
    ],
  },
  {
    letter: 'Q',
    countries: [{ code: 'QA', name: '卡塔尔' }],
  },
  {
    letter: 'R',
    countries: [
      { code: 'RO', name: '罗马尼亚' },
      { code: 'RU', name: '俄罗斯' },
      { code: 'RW', name: '卢旺达' },
    ],
  },
  {
    letter: 'S',
    countries: [
      { code: 'SA', name: '沙特阿拉伯' },
      { code: 'SN', name: '塞内加尔' },
      { code: 'RS', name: '塞尔维亚' },
      { code: 'SG', name: '新加坡' },
      { code: 'SK', name: '斯洛伐克' },
      { code: 'SI', name: '斯洛文尼亚' },
      { code: 'SO', name: '索马里' },
      { code: 'ZA', name: '南非' },
      { code: 'ES', name: '西班牙' },
      { code: 'LK', name: '斯里兰卡' },
      { code: 'SD', name: '���丹' },
      { code: 'SE', name: '瑞典' },
      { code: 'CH', name: '瑞士' },
      { code: 'SY', name: '叙利亚' },
    ],
  },
  {
    letter: 'T',
    countries: [
      { code: 'TW', name: '中国台湾' },
      { code: 'TJ', name: '塔吉克斯坦' },
      { code: 'TZ', name: '坦桑尼亚' },
      { code: 'TH', name: '泰国' },
      { code: 'TL', name: '东帝汶' },
      { code: 'TG', name: '多哥' },
      { code: 'TO', name: '汤加' },
      { code: 'TN', name: '突尼斯' },
      { code: 'TR', name: '土耳其' },
      { code: 'TM', name: '土库曼斯坦' },
    ],
  },
  {
    letter: 'U',
    countries: [
      { code: 'UG', name: '乌干达' },
      { code: 'UA', name: '乌克兰' },
      { code: 'AE', name: '阿联酋' },
      { code: 'GB', name: '英国' },
      { code: 'US', name: '美国' },
      { code: 'UY', name: '乌拉圭' },
      { code: 'UZ', name: '乌兹别克斯坦' },
    ],
  },
  {
    letter: 'V',
    countries: [
      { code: 'VA', name: '梵蒂冈' },
      { code: 'VE', name: '委内瑞拉' },
      { code: 'VN', name: '越南' },
    ],
  },
  {
    letter: 'Y',
    countries: [{ code: 'YE', name: '也门' }],
  },
  {
    letter: 'Z',
    countries: [
      { code: 'ZM', name: '赞比亚' },
      { code: 'ZW', name: '津巴布韦' },
    ],
  },
];
